# List of providers as an array of strings
providers = ["node"]

[phases.setup]
commands = [
  "corepack enable",
  "corepack prepare pnpm@9.1.0 --activate"
]

[phases.install]
commands = ["pnpm install"]

[phases.build]
commands = ["pnpm build"]

[start]
command = "pnpm start"
